GET http://localhost:3000/orders/686e8ac21e3ea65872780f62 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk5MGYxZGVhYmRiNDNjMjEzNWFjMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjUwMTk4NywiZXhwIjoxNzUzMTA2Nzg3fQ.ceR4ZWVcKlPbxeRioI9bCyhOMF0wSiDhGDL8aOPOUvg