DELETE http://localhost:3000/products/6855727f15e2bc416558a43a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk5MGYxZGVhYmRiNDNjMjEzNWFjMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MzEwOTY4NiwiZXhwIjoxNzUzNzE0NDg2fQ.x7OvZYwTfPBtIlyM6W4Ths1nPC0uWkZrit4cOUT492U