DELETE http://localhost:3000/products/6855721715e2bc416558a42e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk5MGYxZGVhYmRiNDNjMjEzNWFjMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDI1ODcwMCwiZXhwIjoxNzUwODYzNTAwfQ.WadSU786qAs6bK_QDd7thz129-oYu91ZqYraK3ouzmA